"""Collection subpackage — content gathering, command execution, mode strategies."""

from .collector import (
    _MANIFEST,
    _build_toc,
    _clean_numbered_files,
    _find_next_part_num,
    _format_toc_entry,
    _get_lock_functions,
    _merge_lock,
    _write_diff_parts,
    _write_parts,
    clean_manifest,
    collect,
    load_manifest,
    save_manifest,
)
from .gatherer import (
    _assemble_command_content,
    _assemble_content,
    _assemble_file_content,
    _scan_directories,
    dry_run,
    gather_command,
    gather_files,
)
from .gatherer_commands import (
    _collect_pre_commands,
)
from .gatherer_files import (
    _collect_directory_sections,
    _collect_file_sections,
    _collect_named_sections,
    _format_file_list,
    _format_one_file,
    _get_exclude_patterns,
    _get_profile_files,
    _print_compress_stats,
    _scan_directory_pattern,
    _scan_one_directory,
)
from .gatherer_files import (
    _scan_directories as _gatherer_scan_directories,
)
from .gatherer_query import (
    _build_reverse_graph,
    _collect_import_graph,
    _expand_import_chain,
    _filter_by_query,
    _filter_filenames_by_query,
    _score_files,
)
from .gatherer_strategies import (
    _assemble_in_memory,
    _FullModeStrategy,
    _HeadersModeStrategy,
    _RepoMapModeStrategy,
    get_mode_strategies,
)

__all__ = [
    "_MANIFEST",
    "_FullModeStrategy",
    "_HeadersModeStrategy",
    "_RepoMapModeStrategy",
    "_assemble_command_content",
    "_assemble_content",
    "_assemble_file_content",
    "_assemble_in_memory",
    "_build_reverse_graph",
    "_build_toc",
    "_clean_numbered_files",
    "_collect_directory_sections",
    "_collect_file_sections",
    "_collect_import_graph",
    "_collect_named_sections",
    "_collect_pre_commands",
    "_expand_import_chain",
    "_filter_by_query",
    "_filter_filenames_by_query",
    "_find_next_part_num",
    "_format_file_list",
    "_format_one_file",
    "_format_toc_entry",
    "_gatherer_scan_directories",
    "_get_exclude_patterns",
    "_get_lock_functions",
    "_get_profile_files",
    "_merge_lock",
    "_print_compress_stats",
    "_scan_directory_pattern",
    "_scan_directories",
    "_scan_one_directory",
    "_score_files",
    "_write_diff_parts",
    "_write_parts",
    "clean_manifest",
    "collect",
    "dry_run",
    "gather_command",
    "gather_files",
    "get_mode_strategies",
    "load_manifest",
    "save_manifest",
]
