# Copyright (C) 2026 Artem Terenin / arachna — AGPLv3
"""Snapshot orchestration — create, update, compute_diff via store and differ."""

from .snapshot_diff import (
    _content_hash,
    _format_summary_header,
    _get_profile_from_manifest,
    _group_diff_sections,
    _is_binary_content,
    collect_snapshot_content,
    compute_diff,
    create_snapshot,
    update_snapshot,
)
from .snapshot_diff_commands import (
    _build_current_pre_commands,
    _build_pre_command_map,
    _collect_snapshot_command,
    _collect_snapshot_pre_commands,
    _diff_cmd_added,
    _diff_cmd_deleted,
    _diff_cmd_modified,
    _diff_command_section,
    _diff_existing_pre_command,
    _diff_new_pre_command,
    _diff_pre_commands_line,
    _diff_pre_commands_marker,
    _diff_pre_commands_sections,
    _diff_pre_commands_structural,
    _get_current_cmd_output,
)
from .snapshot_diff_files import (
    _build_current_files,
    _build_deleted_added_dicts,
    _build_snapshot_files_dict,
    _build_target_files_dict,
    _collect_snapshot_files,
    _diff_file_sets,
    _diff_files_sections,
    _get_content_from_manifest,
    _path_matches_profile,
    _read_file_from_disk,
    _read_file_from_store,
    _read_profile_files,
)
from .snapshot_diff_helpers import (
    _normalize_path,
    _rel_path,
)
from .snapshot_diff_repo_map import (
    _format_repo_map_added,
    _format_repo_map_diff,
    _format_repo_map_entry,
    _get_snapshot_files,
    _parse_blocks_for_lang,
    _repo_map_added_section,
    _repo_map_deleted_section,
    _repo_map_modified_section,
    apply_repo_map_to_sections,
)
from .snapshot_rename import (
    _detect_renames_and_moves,
    _match_exact_renames,
    _match_similar_renames,
)

__all__ = [
    "apply_repo_map_to_sections",
    "collect_snapshot_content",
    "compute_diff",
    "create_snapshot",
    "update_snapshot",
    "_build_current_files",
    "_build_current_pre_commands",
    "_build_deleted_added_dicts",
    "_build_pre_command_map",
    "_build_snapshot_files_dict",
    "_build_target_files_dict",
    "_collect_snapshot_command",
    "_collect_snapshot_files",
    "_collect_snapshot_pre_commands",
    "_content_hash",
    "_detect_renames_and_moves",
    "_diff_cmd_added",
    "_diff_cmd_deleted",
    "_diff_cmd_modified",
    "_diff_command_section",
    "_diff_existing_pre_command",
    "_diff_file_sets",
    "_diff_files_sections",
    "_diff_new_pre_command",
    "_diff_pre_commands_line",
    "_diff_pre_commands_marker",
    "_diff_pre_commands_sections",
    "_diff_pre_commands_structural",
    "_format_repo_map_added",
    "_format_repo_map_diff",
    "_format_repo_map_entry",
    "_format_summary_header",
    "_get_content_from_manifest",
    "_get_current_cmd_output",
    "_get_profile_from_manifest",
    "_get_snapshot_files",
    "_group_diff_sections",
    "_is_binary_content",
    "_match_exact_renames",
    "_match_similar_renames",
    "_normalize_path",
    "_parse_blocks_for_lang",
    "_path_matches_profile",
    "_read_file_from_disk",
    "_read_file_from_store",
    "_read_profile_files",
    "_rel_path",
    "_repo_map_added_section",
    "_repo_map_deleted_section",
    "_repo_map_modified_section",
]
