repos:
  - repo: local
    hooks:
      - id: format
        name: format (ruff)
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
      - id: trailing-ws
        name: trailing whitespace
        entry: make trailing-ws
        language: system
        pass_filenames: false
        always_run: true
      - id: unit-tests
        name: unit tests
        entry: python -m pytest tests/ -v --ignore=tests/benchmark
        language: system
        pass_filenames: false
        always_run: true
