repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: python -m pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true
