sonar.projectKey=dead-duke_arachna
sonar.organization=dead-duke
sonar.host.url=https://sonarcloud.io
sonar.sources=src/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11,3.12,3.13,3.14
